name: test-e2e
on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - '.changelog/**'
      - '.tours/**'
      - 'contributing/**'
      - 'demo/**'
      - 'dev/**'
      - 'e2e/terraform/**'
      - 'e2e/ui/**'
      - 'integrations/**'
      - 'pkg/**'
      - 'scripts/**'
      - 'terraform/**'
      - 'ui/**'
      - 'website/**'
  push:
    branches:
      - main
      - release/**
      - convert-hashicorp-nomad-to-actions-20230505-212504
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - '.changelog/**'
      - '.tours/**'
      - 'contributing/**'
      - 'demo/**'
      - 'dev/**'
      - 'e2e/terraform/**'
      - 'e2e/ui/**'
      - 'integrations/**'
      - 'pkg/**'
      - 'scripts/**'
      - 'terraform/**'
      - 'ui/**'
      - 'website/**'

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Setup go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version-file: ".go-version"
      - run: make deps
      - uses: "./.github/actions/install-buf"
      - run: make generate-structs
      - name: prepare ui cache
        run: |-
          git config --global --add safe.directory /__w/nomad/nomad
          git log -n 1 --pretty=format:%H ui > /tmp/ui-sha
      - name: prepare ui
        run: |-
          if [[ -f ~/tmp/ui-assets/bindata_assetfs.go ]]; then
            cp /tmp/ui-assets/bindata_assetfs.go ./command/agent/bindata_assetfs.go
            exit 0
          fi
          ./scripts/vagrant-linux-unpriv-ui.sh
          export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
          export PATH="$GOPATH/bin:/usr/local/go/bin:$PATH"
          # shellcheck source=./.nvm/nvm.sh
          . ~/.nvm/nvm.sh
          cd ui && yarn install --frozen-lockfile && cd ..
          JOBS=2 make ember-dist static-assets
          mkdir -p /tmp/ui-assets
          cp ./command/agent/bindata_assetfs.go /tmp/ui-assets/bindata_assetfs.go
      - name: build binaries
        run: |-
          go_tags="ui $(grep -e '^GO_TAGS ?=' ./GNUmakefile | cut -d= -f2)"
          export GO_TAGS="$go_tags"
          make pkg/windows_amd64.zip pkg/linux_amd64.zip
      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          path: pkg
      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          path: "/tmp/ui-assets"
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Setup go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
      - run: make deps
      - run: make integration-test
      - run: make e2e-test
permissions:
  contents: read
